### ISSUE TITLE
Cant cache measurements for wikitext or squad_v2

### ISSUE THREAD

**Issue by freddyaboulton** [huggingface/data-measurements-tool#42]
When I run

```
python3 run_data_measurements.py --dataset="wikitext" --config="wikitext-103-v1" --split="train" --feature="text"
```

I get the following (abridged stacktrace)
```
data_measurements_tool] {/Users/freddy/sources/data-measurements-tool/data_measurements/labels/labels.py:198} labels INFO - Inside main label calculation function.
[data_measurements_tool] {/Users/freddy/sources/data-measurements-tool/run_data_measurements.py:330} run_data_measurements ERROR - "Column label not in the dataset. Current columns in the dataset: ['text']"
Traceback (most recent call last):
  File "/Users/freddy/sources/data-measurements-tool/run_data_measurements.py", line 306, in main
    pass_args_to_DMT(
  File "/Users/freddy/sources/data-measurements-tool/run_data_measurements.py", line 157, in pass_args_to_DMT
    load_or_prepare(dataset_args, calculation=calculation, use_cache=use_cache)
  File "/Users/freddy/sources/data-measurements-tool/run_data_measurements.py", line 99, in load_or_prepare
    dstats.load_or_prepare_labels()
  File "/Users/freddy/sources/data-measurements-tool/data_measurements/dataset_statistics.py", line 346, in load_or_prepare_labels
    label_obj.run_DMT_processing()
  File "/Users/freddy/sources/data-measurements-tool/data_measurements/labels/labels.py", line 122, in run_DMT_processing
    self.label_results = self._prepare_labels()
  File "/Users/freddy/sources/data-measurements-tool/data_measurements/labels/labels.py", line 161, in _prepare_labels
    label_results = label_obj.prepare_labels(label_field, self.label_names)
  File "/Users/freddy/sources/data-measurements-tool/data_measurements/labels/labels.py", line 201, in prepare_labels
    label_list = self.dset[label_field]
  File "/Users/freddy/miniconda3/envs/data-measurements/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2154, in __getitem__
    return self._getitem(
  File "/Users/freddy/miniconda3/envs/data-measurements/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2138, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices if self._indices is not None else None)
  File "/Users/freddy/miniconda3/envs/data-measurements/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 483, in query_table
    _check_valid_column_key(key, table.column_names)
  File "/Users/freddy/miniconda3/envs/data-measurements/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 423, in _check_valid_column_key
    raise KeyError(f"Column {key} not in the dataset. Current columns in the dataset: {columns}")
KeyError: "Column label not in the dataset. Current columns in the dataset: ['text']"
[data_measurements_tool] {/Users/freddy/sources/data-measurements-tool/run_data_measurements.py:338} run_data_measurements WARNING - Data measurements not computed. ☹️
```

I thought this may have been because of the missing `label_field` parameter. When I add it:

```
python3 run_data_measurements.py --dataset="wikitext" --config="wikitext-103-v1" --split="train" --feature="text" --label_field="text"
```

I still get an error (but it's different)

```
[data_measurements_tool] {/Users/freddy/sources/data-measurements-tool/data_measurements/labels/labels.py:198} labels INFO - Inside main label calculation function.
[data_measurements_tool] {/Users/freddy/sources/data-measurements-tool/run_data_measurements.py:330} run_data_measurements ERROR - 'text'
Traceback (most recent call last):
  File "/Users/freddy/sources/data-measurements-tool/run_data_measurements.py", line 306, in main
    pass_args_to_DMT(
  File "/Users/freddy/sources/data-measurements-tool/run_data_measurements.py", line 157, in pass_args_to_DMT
    load_or_prepare(dataset_args, calculation=calculation, use_cache=use_cache)
  File "/Users/freddy/sources/data-measurements-tool/run_data_measurements.py", line 99, in load_or_prepare
    dstats.load_or_prepare_labels()
  File "/Users/freddy/sources/data-measurements-tool/data_measurements/dataset_statistics.py", line 346, in load_or_prepare_labels
    label_obj.run_DMT_processing()
  File "/Users/freddy/sources/data-measurements-tool/data_measurements/labels/labels.py", line 122, in run_DMT_processing
    self.label_results = self._prepare_labels()
  File "/Users/freddy/sources/data-measurements-tool/data_measurements/labels/labels.py", line 161, in _prepare_labels
    label_results = label_obj.prepare_labels(label_field, self.label_names)
  File "/Users/freddy/sources/data-measurements-tool/data_measurements/labels/labels.py", line 213, in prepare_labels
    label_names = extract_label_names(label_field, self.ds_name,
  File "/Users/freddy/sources/data-measurements-tool/data_measurements/labels/labels.py", line 66, in extract_label_names
    label_names = map_labels(label_field, ds_name_to_dict, ds_name, config_name)
  File "/Users/freddy/sources/data-measurements-tool/data_measurements/labels/labels.py", line 30, in map_labels
    ds_name_to_dict[ds_name][config_name]["features"][label_field]) > 0
KeyError: 'text'
[data_measurements_tool] {/Users/freddy/sources/data-measurements-tool/run_data_measurements.py:338} run_data_measurements WARNING - Data measurements not computed. ☹️
```

**Comment by freddyaboulton** [comment]
Same stacktrace on squad_v2

**Comment by freddyaboulton** [comment]
For imdb I get

```
_measurements ERROR - All arguments should have the same length. The length of argument `values` is 1, whereas the length of  previously-processed arguments ['names'] is 2
Traceback (most recent call last):
  File "/Users/freddy/sources/data-measurements-tool/run_data_measurements.py", line 306, in main
    pass_args_to_DMT(
  File "/Users/freddy/sources/data-measurements-tool/run_data_measurements.py", line 157, in pass_args_to_DMT
    load_or_prepare(dataset_args, calculation=calculation, use_cache=use_cache)
  File "/Users/freddy/sources/data-measurements-tool/run_data_measurements.py", line 99, in load_or_prepare
    dstats.load_or_prepare_labels()
  File "/Users/freddy/sources/data-measurements-tool/data_measurements/dataset_statistics.py", line 346, in load_or_prepare_labels
    label_obj.run_DMT_processing()
  File "/Users/freddy/sources/data-measurements-tool/data_measurements/labels/labels.py", line 127, in run_DMT_processing
    make_label_fig(self.label_results)
  File "/Users/freddy/sources/data-measurements-tool/data_measurements/labels/labels.py", line 55, in make_label_fig
    fig_labels = px.pie(names=label_names, values=label_sums)
  File "/Users/freddy/miniconda3/envs/data-measurements/lib/python3.9/site-packages/plotly/express/_chart_types.py", line 1458, in pie
    return make_figure(
  File "/Users/freddy/miniconda3/envs/data-measurements/lib/python3.9/site-packages/plotly/express/_core.py", line 1933, in make_figure
    args = build_dataframe(args, constructor)
  File "/Users/freddy/miniconda3/envs/data-measurements/lib/python3.9/site-packages/plotly/express/_core.py", line 1405, in build_dataframe
    df_output, wide_id_vars = process_args_into_dataframe(
  File "/Users/freddy/miniconda3/envs/data-measurements/lib/python3.9/site-packages/plotly/express/_core.py", line 1245, in process_args_into_dataframe
    raise ValueError(
ValueError: All arguments should have the same length. The length of argument `values` is 1, whereas the length of  previously-processed arguments ['names'] is 2
```

**Comment by meg-huggingface** [comment]
Thanks for this -- checking it out now.

**Comment by meg-huggingface** [comment]
Wikitext doesn't have a "label" column nor anything comparable it appears (https://huggingface.co/datasets/wikitext), same with squad_v2 (https://huggingface.co/datasets/squad_v2).
In that case, the code should just move on from trying to do anything about labels. 
Adding if...else... statements to gracefully move on when the label field isn't there. Will send PR shortly.

**Comment by meg-huggingface** [comment]
Regarding the wikitext/squad_v2 issue: https://github.com/huggingface/data-measurements-tool/pull/44

**Comment by meg-huggingface** [comment]
Regarding IMDB: I can't repro, can you write the command you're using?

**Comment by freddyaboulton** [comment]
Thanks @meg-huggingface ! I was running 

```
python3 run_data_measurements.py --dataset="imdb" --config="plain_text" --split="unsupervised" --label_field="label" --feature="text"
```
